### ISSUE TITLE
Automatically create PR when the template updates

### ISSUE THREAD

**Issue by KostyaEsmukov** [rambler-digital-solutions/scaraplate#1]
We, Rambler Usermodel, internally run a periodic task which rolls up corresponding templates on the projects which are under scaraplate. If there's a git diff after the rollup (i.e. the template has updated, or the target project has changed something which diverges from the template), a pull request is automatically created, which then is getting merged by a human.

It works pretty well, however, the task implementation is very specific to our infrastructure.

It would be great to open-source this somehow, so others could benefit from this kind of automation as well.

**Comment by arpitremarkable** [comment]
Hey, first of all, love the problem this project aims to solve and I hope we can use this project for our next cookiecutter template (we're facing some issues but don't wanna crib about it right now)
.
Anyway, this feature of "Automatically create PR" looks great at first but I just wanna know if this goes against this project's _fundamental_ philosophy of "scaraplate makes no assumptions about the code versioning system used by the target project"
.
I mean PR as a concept doesn't really exist in VCS anyway, it's more of a feature provided by the VCS hosting provider (github, gitlab). So, this feature is aimed more towards specific hosting providers than even whole of GIT or HG. Example: after looking at the pull request changes in https://github.com/rambler-digital-solutions/scaraplate/pull/11/ I don't think BitBucket is supported.
.
Honestly, I would love for this feature to be there but I don't think it aligns with the vision of this project (from what I understand)
And if this feature doesn't come up in future then I can probably use my VCS hosting provider's webhooks and APIs and zapier-esque service to achieve this automation.

**Comment by KostyaEsmukov** [comment]
Thank you for the question! Let me try to explain my vision on this.

1. `scaraplate rollup` commands and `scaraplate.automation` package (which is still work in progress in #11) are intentionally separated. `scaraplate.automation` uses `rollup`, but not the other way. That said, the automation part doesn't have to be used: one might automate `rollup` by their own means.

2. The `rollup` part stands firm by this claim of "scaraplate makes no assumptions about the code versioning system used by the target project". 

   Hovewer, the **target project** part should be emphasised, because for template scaraplate (at this moment) **does** assume that it is located in a git repo (see https://scaraplate.readthedocs.io/en/latest/gitremotes.html#module-scaraplate.gitremotes). This is something I would like to be changed, but unfortunately I don't see any other ways to transparently collect a template's metadata rather than querying a specific template's VCS. That said, we can easily get rid of requirement of git by adding support for other VCS used by templates, but eliminating the knowledge about VCS in templates completely doesn't seem viable to me.

3. The `scaraplate.automation` from #11 consists of 3 layers:
- `scaraplate.automation.base` -- it contains the wrapper for automation and defines 2 abstract classes:
  * `TemplateVCS` which should retrieve the template (which, as said before, has to be a git repo)
  * `ProjectVCS` which should retrieve the project and allow to push back the changes (there're no assumptions made about VCS here)
- `scaraplate.automation.git` -- it contains implementations of `TemplateVCS` and `ProjectVCS` for git projects. There're no assumptions made about specific git remote providers here. This part can easily be reused for GitLab, GitHub, BitBucket (for git) and so on. But it doesn't open Pull Requests, it just uses plain `git` for issuing `git clone`, `git commit` and `git push`.
- `scaraplate.automation.gitlab` -- it extends `scaraplate.automation.git` implementations for simplifying integration with GitLab: it generates gitlab-specific clone URLs (which is useful for projects which cannot be cloned without authentication) and contains Merge Request creation after a commit to the target project.

--

> I don't think BitBucket git users are supported.

Indeed, BitBucket is not supported out of box. Unfortunately, the Pull Request entity is implemented differently between different git remote providers, so this part cannot (as far as I know) be easily reused between all providers. For example, to open a Merge Request in GitLab, something has to call their API. For GitHub this API is different. Something has to implement this, and there's no other way than to make specific API calls to specific providers.

That said, for BitBucket specifically, automation can be implemented as:
1. For git repositories, by extending `scaraplate.automation.git` classes with BitBucket-specific clone URL generation and Pull Request creation. `scaraplate.automation.gitlab` classes should be a good example of how to add support for a specific provider.
2. For mercurial, by extending `scaraplate.automation.base` similarly to `scaraplate.automation.git`, but for mercurial. And then the other layer for Pull Request (as in the first point).

In #11 the only specific git remote provider which is going to be added is GitLab, but we are happy to accept PRs for adding other providers as well.

--

Scaraplate is very extensible, and I tend to think of *that* as fundamental philosophy of the project rather than of it abstracting away from VCS as much as it can. So the core parts of scaraplate indeed make as less assumptions as possible, but the outer parts get more specific by simplifying common usecases at the cost of making more assumptions.

But as long as the outer parts are replacable (and they are!), the claim of "scaraplate makes no assumptions about the code versioning system used by the target project" stands true.

I think that part needs to be clarified in docs.
