### ISSUE TITLE
Could pyyaml be unpinned to higher version than 4?

### ISSUE THREAD

**Issue by tlvu** [rambler-digital-solutions/scaraplate#18]
https://github.com/rambler-digital-solutions/scaraplate/blob/96011f31015e962ad9388f0873e8196abecbe64d/setup.cfg#L100

It's breaking the install when installing together with other tools for a one stop shop environment.

**Comment by KostyaEsmukov** [comment]
I have no idea what does "one stop shop environment" mean, but I guess we can easily change it to `pyyaml>=3,<6`.

Would you like to open a PR?

**Comment by KostyaEsmukov** [comment]
Oh, there's already #17 open

**Comment by KostyaEsmukov** [comment]
Fixed in 22f4eecbe1b5e917a38e399334fc7e21fb1d4ae7, going to release on pypi soon.

**Comment by KostyaEsmukov** [comment]
Released on pypi: `pip install scaraplate==0.3`

**Comment by tlvu** [comment]
> I have no idea what does "one stop shop environment" mean

I just mean it can be installed together with other packages without conflicting with their requirements.

Thanks a lot for the release.  I had started the exact same patch https://github.com/tlvu/scaraplate/commit/4602a26c31a614052906ec3d78fda45b2765b156 and was going to PR once I use it successfully.

**Comment by KostyaEsmukov** [comment]
> I just mean it can be installed together with other packages without conflicting with their requirements.

Got it, thanks. I assumed it meant conflicts with other packages, so I have added support for a newer marshmallow version as well.

**Comment by tlvu** [comment]
> I assumed it meant conflicts with other packages

Yes.

> so I have added support for a newer marshmallow version as well.

Thanks !
