### ISSUE TITLE
question about post_gen hook

### ISSUE THREAD

**Issue by pouledodue** [rambler-digital-solutions/scaraplate#5]
Hi
Is [this](https://github.com/cookiecutter/cookiecutter/issues/723#issuecomment-350561930) supposed to work with Scaraplate?
In cookiecutter it works but in Scaraplate it does not seem to remove files

**Comment by KostyaEsmukov** [comment]
The hooks do work, but the files are removed from the temporary project, not from the target one. See https://scaraplate.readthedocs.io/en/latest/template.html#create-files-conditionally

Removing files from the target project by scaraplate is intentionally not supported, see https://scaraplate.readthedocs.io/en/latest/template.html#restructuring-files

However, if you could share your usecase, we might try to come up with a solution.
